version: '3'
services:
  mongodb:
    image: mongo:5
    command: mongod --logpath=/dev/null 
    ports: 
      - 27017:27017

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb+srv://gmartinezc4:cristiano7@cluster0.ltpbs.mongodb.net/?retryWrites=true&w=majority 
    depends_on:
      - mongodb
    ports:
      - 6005:6005

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://back:6005
    depends_on:
      - back
    ports:
      - 3000:3000